### ISSUE TITLE
项目运行环境

### ISSUE THREAD

**Issue by Triple-Z** [Alen-gao/IM-Socket.io#5]
项目是否需要 MongoDB 数据库？

在运行 `server` 时，`npm start` 后的错误栈：
```bash
(node:23845) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
connection error: { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/home/triplez/Code/IM-Socket.io/server/node_modules/_mongodb-core@2.1.17@mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:115:13)
    at Pool.emit (events.js:210:7)
    at Connection.<anonymous> (/home/triplez/Code/IM-Socket.io/server/node_modules/_mongodb-core@2.1.17@mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at Connection.emit (events.js:213:7)
    at Socket.<anonymous> (/home/triplez/Code/IM-Socket.io/server/node_modules/_mongodb-core@2.1.17@mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'MongoError',
  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }

```

**Comment by Triple-Z** [comment]
是因为我没安装 `MongoDB` 么？

**Comment by alphaobj** [comment]
对windows不太友好啊

**Comment by LanjianNUll** [comment]
你的mongodb要启动起来
